### ISSUE TITLE
Some test data

### ISSUE THREAD

**Issue by ghost** [ethz-ait/klt_feature_tracker#5]
Hi
1. Is it possible to provide some test data to demo the capability of this library? 
1. In the function, `trackFeatures(const cv::Mat &img_l, const cv::Mat &img_r, std::vector<cv::Point2f> &features_l, std::vector<cv::Point2f> &features_r, std::vector<int> &status, int stereo)`, how is `std::vector<int> &status` initialized?

Thanks.

**Comment by ndepal** [comment]
1. I don't have any test data at hand, but you can very easily test it with any set of images that you load with openCV. If you have a camera that publishes images on a ROS topic, you can write a simple node that calls the `TrackFeatures` service which wraps the `trackFeatuers` call.

2. `std::vector<int> &status` needs to be initialized by the user of the library. Create a status vector with the size that matches your desired number of tracked features. The initial value of each `status[i]` can be chosen by you, depending on your needs. E.g. to initialize all `n` features on the first function call, initialize as follows:
```std::vector<int> status(n, 2);```
You may only want to use a subset of the total trackable features during the first call, so you might do e.g.:
```
std::vector<int> status(n, 0); // n is the number of features to track, default all to inactive
for (int i = 0; i < 10; i++) { // assuming n > 10
    status[i] = 2;  // request the first 10 features to be initialized
}
```

**Comment by tnaegeli** [comment]
I actaully have a rosbag with test data. i try to upload it somewhere and
make a link to the test data.

2017-02-06 10:25 GMT+01:00 Nicolas de Palezieux <notifications@github.com>:
